### ISSUE TITLE
Standard Error Redirection 

### ISSUE THREAD

**Issue by josephliccini** [jeanralphaviles/jsh#10]
Redirect standard error to either a file or standard out.

As per spec:
The construct 2>file redirects the standard error of the program to file, while 2>&1 connects the standard error of the program to its standard output.

**Comment by jeanralphaviles** [comment]
STDERR redirection implemented in c288752f3b130bfcd43e1cf1b16bc3ffced09df5
I'll start work on connecting stderr to stdout once I finish my signals homework.

**Comment by jeanralphaviles** [comment]
Added connecting stderr to stdout
e33ca776855e6cc56fb713a05d3b4d22a861b062
