### ISSUE TITLE
Wildcard Matching 

### ISSUE THREAD

**Issue by josephliccini** [jeanralphaviles/jsh#6]
Implement '*' and '?' as patterns.

Spec says:
You will implement a subset of the functionality found in most shells. Before a command is executed, each command word should be scanned for the characters \* and ?. If one of these characters appears the word is regarded as a pattern. The word is replaced with alphabetically sorted filenames that match the pattern. If no filename is found that matches the pattern, the word is left unchanged.
A \* matches any string, including the null string. A ? matches any single character. The character ‘.’ at the start of a filename or immediately following a ‘/’, as well as the character ‘/’ itself, must be matched explicitly.

**Comment by jeanralphaviles** [comment]
- Matching
  7f15a3204cf1ddfa4fc2c5eec6e87e32d8117935
  ? Matching
  c6b7ec1b1648bccc736ec4f345a35acc2c71cba2

**Comment by jeanralphaviles** [comment]
Also, the TILDE expansion bonus was included :)
